---
name: Test
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest]
        cgo-enabled: [0, 1]
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: ${{ matrix.cgo-enabled }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
